### PR TITLE
authenticate function call signature has changed since Django 1.11

### PR DESCRIPTION
**Pull request by daleobrien**
Please see:
https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.backends.ModelBackend.authenticate

This fix adds the request parameter for the authenticate function call. I've also added a Change log.

### CODE REVIEW

**Comment by aaugustin** [comment]
Thanks for the suggestion.

I don't think this makes any difference in practice:

- only the django-sesame authentication backend is supposed to the `url_auth_token` parameter
- `UrlAuthBackendMixin.authenticate` ignores the `request` argument

However, it may be more future proof and it feels a bit cleaner, so why not.

I'm planning to pick just the change to `utils.py` and not mention it in the changelog, unless you can explain a use case that users would care about.

**Comment by aaugustin** [comment]
Patch edited and committed in b3a94352f5d907063af03c8aec44f14a7c09da6f.

**Comment by aaugustin** [comment]
I realized after the fact that django-sesame doesn't have a changelog. It would be good to add one. I created #31 to keep track of this.

**Comment by daleobrien** [comment]
Hi,

The change log isn't that import to reflect all the history before now, no point in making lots of work for yourself, but is very useful when you make a new release.  I scan all my project's package when updating them to make sure they are no breaking changes.  Most projects have a separate change log file.

I'm using other backends for authentication as well, namely https://github.com/jazzband/django-axes and without the request parameter in your project it will fail. I'm guessing If I had changed the order of my AUTHENTICATION_BACKENDS I might not have seen the problem, yours is before `axes`.  I do know when I added the request parameter, all is well again and I see you have patched your project, so that's great.

Your setup.py file doesn't reflect the current PIP version, I'm not sure, but that might cause issues with reinstalling from PIP.

Can you update https://pypi.org/project/django-sesame/ to reflect the patch? That way I can revert to using you pip repo again and delete my fork.

Thanks,
Dale

**Comment by aaugustin** [comment]
I'm familiar with the usefulness of a changelog. If a user is currently on version 1.2, I believe that having a changelog that starts on version 1.5 is even more disappointing than no changelog at all, which is why I'd rather go back to the beginning than start midway.

----

You hit this issue because django-axes requires the `request` parameter to be passed to all `authenticate()` calls. This is a stronger requirement than what Django specifies.

Its documentation provides detailed instructions on how to make this happen with various authentication backends: https://django-axes.readthedocs.io/en/latest/6_integration.html

If django-sesames was more popular, perhaps they would have included a 20 line patch to work around the issue :-) Anyway it was clearly easier to fix here.

----

I'll push a new release when #29 is resolved.

**Comment by aaugustin** [comment]
I released version 1.7 (and also added a changelog).

**Pull request closed without merging**
