### PR TITLE
Interpolate view arguments in decorator scope.

### PR DESCRIPTION
**Pull request by aaugustin**
Typical use of scope is: scope=f"object_type:{object_id}". This change
makes it possible to use the decorator with such scopes, as follows:

    @authenticate(scope="object_type:{object_id}")
    def view(request, object_id):
        ...

### CODE REVIEW

**Comment by aaugustin** [comment]
I'm 95% sure it's a convenient API.

The 5% of doubt stem from the "magic" aspect of interpolation. It may come as a surprise if someone uses significant characters in scope names without expecting interpolation. However, I would expect scopes to be "slugs" in general, so this is unlikely to cause issues. If we get complaints, we could add a try/catch around `scope.format(*args, **kwargs)` and give an error message that clarifies the situation.

**Comment by aaugustin** [comment]
Opinions welcome!

**Comment by aaugustin** [comment]
No backwards-compatibility concerns as this is a new API is the next version of django-sesame.

**Comment by adamchainz** [comment]
This looks like a good addition, nice one.

**Pull request merged**
