### PR TITLE
Fix redirecting get request with query string

### PR DESCRIPTION
**Pull request by caduri**
Hi @aaugustin 
I'm not sure why but redirecting with query string adds a weird `'` at the end of the param. 
Following this [https://stackoverflow.com/a/3766503/2302131](url) SO answer I created this PR

### CODE REVIEW

**Comment by aaugustin** [comment]
Hello, the SO answer you're pointing to says nothing about a stray `'` and I'm not sure why the changes you're proposing would change the behavior.

Can you show me how to reproduce the problem?

**Comment by aaugustin** [comment]
Or at least provide more details about the issue you're encountering?

**Comment by caduri** [comment]
Hi @aaugustin I'm sorry I don't have more info on this issue
googling the issue I saw that this is a common issue with a solution(which works in my case)
thats why I didn't tried to create a demo app to reproduce it

**Comment by caduri** [comment]
downgrading sesame to 1.3(without the redirect) its also working in my case
that's why my immediate suspect was the redirect

I don't have much time this week but I might be able to clear some time and do a demo app on the weekend, let me know if its needed

**Comment by aaugustin** [comment]
If your PR changes something, it means there's a bug in the implementation of Django's `redirect` function.

The bug should be fixed there rather than worked around in every library and app that calls `redirect`.

**Comment by caduri** [comment]
You are definitely right, when I investigated the error in my app If I would find the error I definitely would have send a PR to django but I couldn't so I decided to create a workaround for this library so other people won't stumble upon this issue and I plan to file a ticket to django once I create a demo app that reproduce this error without sesame

Don't you think using a workaround until the issue is identified and fixed is acceptable?

**Comment by aaugustin** [comment]
Well, to be honest, at this point I believe that your PR doesn't change anything and that the problem lies somewhere else.

If something was adding a stray `'` this test should fail: https://github.com/aaugustin/django-sesame/blob/88ca7bc947d9047f69e6561d27c3cd13b69ea1b8/sesame/test_middleware.py#L76-L79

**Comment by caduri** [comment]
or maybe this test isn't good enough.

Look I submitted this PR to help and fix an issue I found, related specifically to sesame upgrade from 1.2 to 1.4. after I downgrade to 1.3 it start working again, the only change in the middleware was adding the remove of the token and redirect(which is smart IMO) and this PR fix this issue

If you still have issues with this PR, like I said above I'll create a demo app in the near future hopefully
If you have any constructive ideas of what I can test to help clarify this, I'll be happy to hear them(and not dismissing this PR just cause you don't believe in it)

**Comment by aaugustin** [comment]
I understand that you're trying to help and I appreciate that.

However, I don't like making changes that I don't understand.

I would like to reproduce the issue and to write a test to ensure we don't have regressions in the future.

Otherwise, someone could propose the reverse patch, add a comment saying "simplification - use redirect instead of editing the Location header", and if I forget this discussion, there's a good chance I'lll merge it.

Just a little bit more information could help. Perhaps you could show me the URL before and after redirect (just change some characters in the token). If it's a parsing or serialization issue, that should allow me to reproduce the problem.

**Comment by aaugustin** [comment]
There's already a try / except ImportError to handle the difference in import location between Python 2 and 3. The version check added in this commit is redundant.

**Comment by caduri** [comment]
You probably didn't read what I wrote, My app is able to import urllib.parse and this line `from urllib.parse import urlencode` doesn't throw an exception!

Anyway after pinpointing the issue to the import `from urllib.parse import urlencode` I found out that one of my third parties `zenpy`(wrapper for zendesk) is using futures package http://python-future.org/imports.html#aliased-imports which backport python3 modules to python2 and thats what enables the import `from urllib import urlencode`

@aaugustin as you can see the try/catch is not enough

**Comment by aaugustin** [comment]
> You probably didn't read what I wrote

Thanks. Let's leave it there!

**Comment by aaugustin** [comment]
(For the record, my argument is that:

```
try:
    from urllib import urlencode
except ImportError:
    from urllib import urlencode    
```

isn't useful, and that's the result of https://github.com/aaugustin/django-sesame/pull/12/commits/e755ea012e16dad65cdb654b9feeaf98e0c8d89e on Python 2.)

**Comment by caduri** [comment]
I didn't understand your last comment.

It's your library you can ignore the fact that the code has possible bug in case someone uses futures package, I don't understand why but its your decision

**Pull request closed without merging**
