### PR TITLE
Add support for UUIDs as user.pk

### PR DESCRIPTION
**Pull request by GamePad64**
Relates: #17

### CODE REVIEW

**Comment by GamePad64** [comment]
It is a bit verbose but works like charm. The developer can specify its own serializer, so any primary key type is possible. The existing code will retain existing behavior and backward-compatible.

**Comment by aaugustin** [comment]
Thanks for the pull request. The feature is sound.

I'm wondering if we could improve the implementation by introspecting the primary key of the User model in order to require no configuration.

The `value_to_string` and `to_python` produce more verbose representations than those used by the current code and this PR. I'd rather not make the tokens longer than they need to be, since the primary use case is putting them into emails, and longer URLs degrade the UX. So +1 for having dedicated int and UUID packers.

I would make two improvements to your proposal:

- autodetect the right packer by inspecting the type of the PK of the User model
- initialize the packer in __init__ — this will make the code a bit more readable

Furthermore, it would be nice to have a test for this feature.

Let me know if you're interested in making these improvements or if I should make them.

**Comment by aaugustin** [comment]
Superseded by #21 which includes tests, docs, and the improvements discussed above.

**Comment by aaugustin** [comment]
Thanks for the PR — it was a very good starting point!

**Pull request closed without merging**
